# Generated by Django 5.1.5 on 2025-02-24 09:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpost', '0005_alter_reviewer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='addpost/images'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐', '⭐⭐⭐'), ('⭐', '⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐', '⭐⭐')], max_length=10),
        ),
    ]
