# Generated by Django 5.1.5 on 2025-02-10 08:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_registration_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='ImageUpload',
        ),
        migrations.AlterModelOptions(
            name='imageupload',
            options={'verbose_name_plural': 'ImageUpload'},
        ),
    ]
