# Generated by Django 5.1.5 on 2025-02-25 05:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_registration_imageupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='accounts/images/'),
        ),
    ]
